version: "3.2"
services:
  backend_prod:
    container_name: backend_prod
    build:
      context: ./backend
      args:
        requirements: requirements/production.txt
        # default requirements set to production (will override Dockerfile's default value)
    env_file:
        - ./env/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
    networks:
      - main
    volumes:
      - backendStatic:/backend/backend/static
    depends_on:
      - db
  frontend_prod:
    container_name: frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - main
    depends_on:
      - backend_prod
    volumes:
      - frontendData:/build
  db:
    container_name: db_prod
    image: postgres:alpine
    env_file:
        - ./env/.env.prod.db
    networks:
      - main
    ports:
      - "5432:5432"
  nginx:
    container_name: nginx_prod
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontendData:/frontend:ro
      - backendStatic:/backend/static:ro
    ports:
      - 80:80
      - 8080:8080
    networks:
      - main
    depends_on:
      - frontend_prod
networks:
  main:
volumes:
  frontendData: 
  backendStatic:
