version: "3.2"
services:
  backend:
    build:
      context: ./backend
      args:
        requirements: requirements/development.txt
        # default requirements set to development (will override Dockerfile's default value)
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
    volumes:
      - ./backend:/backend
      # reload server on code changes -- user doesn't have to manually restart Django server each time they make changes
    networks:
      - main
    ports:
      - "8080:8001"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    networks:
      - main
    depends_on:    
      - backend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - main
    ports:
      - "5432:5432"
networks:
  main: