version: "3.2"
services:
  app:
    build:
      context: ./backend
      args:
        requirements: requirements/development.txt
        # default requirements set to development (will override Dockerfile's default value)
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
        #      - path=backend
    volumes:
      - ./:/app
      # reload server on code changes -- user doesn't have to manually restart Django server each time they make changes
    networks:
      - main
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - main
    ports:
      - "5432:5432"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/backend/static:/usr/share/nginx/backend/backend/static
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - app

networks:
  main:
