version: "3.2"
services:
  backend:
    build:
      context: ./backend
      args:
        requirements: requirements/development.txt
        # default requirements set to development (will override Dockerfile's default value)
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
    volumes:
      - ./backend:/backend
      # reload server on code changes -- user doesn't have to manually restart Django server each time they make changes
    networks:
      - main
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    networks:
      - main
    depends_on:    
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - main
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - main
    depends_on:
      - frontend
      - backend
networks:
  main: